PocketJudgeServer/PocketJudgeServer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import app.urls as app_urls
import rest_api.urls as api_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(api_urls)),
    url(r'^', include(app_urls, namespace="app"))
]

PocketJudgeServer/app/urls.py
from datetime import datetime

from django.conf.urls import url
from django.contrib.auth.views import login, logout, logout_then_login
from .views import ContestListView, ContestDetailView, HomeView, project_detail_view
from .forms import BootstrapAuthenticationForm

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^login/$',
        login,
        {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout/$', logout, {'next_page': '/', }, name='logout'),
    url(r'logout-then-login/$', logout_then_login),
    url(r'my-contests/$', ContestListView.as_view(), name='my_contests'),
    url(r'my-contests/(?P<pk>\d+)/$', ContestDetailView.as_view(), name='my_contest_detail'),
    url(r'my-projects/(?P<pk>\d+)/$', project_detail_view, name='my_project_detail')
]

PocketJudgeServer/app/templates/app/base.html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% load static %}
        <link rel="icon" href="{% static 'app/img/favicon.ico' %}">

        <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'app/css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'app/css/main.css' %}">
        <style>
            body {
                padding-top: 70px;
                padding-bottom: 20px;
            }
        </style>

        <script src="{% static 'app/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'app:home' %}">УГТУ - PocketJudge</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'app:my_contests' %}">Мои мероприятия</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container" id="main-container">
      {% block content %}{% endblock %}

      <hr>

      <footer>
        <p>&copy; xMonkIT 2017</p>
      </footer>
    </div> <!-- /container -->
        <script src="{% static 'app/js/vendor/jquery-1.11.2.min.js' %}"></script>

        <script src="{% static 'app/js/vendor/bootstrap.min.js' %}"></script>

        <script src="{% static 'app/js/main.js' %}"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
    </body>
</html>

PocketJudgeServer/app/templates/app/contest.html
{% if contests|length > 0 %}
<ul class="list-group">
{% for contest in contests %}
    <li class="list-group-item">
        <p>{{ contest.name }}</p>
        {% include 'app/projects-table.html' with projects=contest.projects.all %}
        {% include 'app/contest.html' with contests=contest.contests.all %}
    </li>
{% endfor %}
</ul>
{% endif %}

PocketJudgeServer/app/templates/app/contest_detail.html
{% extends 'app/base.html' %}

{% block content %}
    <h2>{{ contest }}</h2>
    <ul class="list-group">
        {% for project in contest.projects.all %}
            <li class="list-group-item">
                <a href="{% url 'app:my_project_detail' project.pk %}">{{ project }}</a>
            </li>
        {% empty %}
            <p>В мероприятии не участвует ни одного проекта.</p>
        {% endfor %}
    </ul>
{% endblock %}

PocketJudgeServer/app/templates/app/contest_list.html
{% extends 'app/base.html' %}

{% block content %}
    <h2>Оцениваемые мероприятия</h2>
    <ul class="list-group">
        {% for contest in contest_list %}
            <li class="list-group-item">
                <a href="{% url 'app:my_contest_detail' contest.pk %}">{{ contest }}</a>
            </li>
        {% empty %}
            <p>Вы не оцениваете ни одного мероприятия.</p>
        {% endfor %}
    </ul>
{% endblock %}

PocketJudgeServer/app/templates/app/home.html
{% extends 'app/base.html' %}

{% block content %}
    {% if contests|length > 0 %}
        {% include 'app/contest.html' %}
    {% else %}
        <p>Отсутствует информация о мероприятиях</p>
    {% endif %}
{% endblock %}

PocketJudgeServer/app/templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}
    {% if contests|length > 0 %}
        {% include 'app/contest.html' %}
    {% else %}
        <p>Отсутствует информация о мероприятиях</p>
    {% endif %}
{% endblock %}

PocketJudgeServer/app/templates/app/login.html
{% extends "app/base.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-3">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="hidden" name="next" value="/" />
                <input type="submit" value="Log in" class="btn btn-default" />
            </form>
        </section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

PocketJudgeServer/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="{% url 'app:logout' %}" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello, {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log out</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'app:login' %}">Log in</a></li>
</ul>

{#<form class="navbar-form navbar-right" role="form">#}
{#    <div class="form-group">#}
{#        <input type="text" placeholder="Имя пользователя" class="form-control">#}
{#    </div>#}
{#    <div class="form-group">#}
{#        <input type="password" placeholder="Password" class="form-control">#}
{#    </div>#}
{#    <button type="submit" class="btn btn-success">Sign in</button>#}
{#</form>#}
{% endif %}

PocketJudgeServer/app/templates/app/project_detail.html
{% extends 'app/base.html' %}

{% block content %}
    <h2>{{ project.name }}</h2>
    <div class="row">
        <div class="col-md-3">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Сохранить" class="btn btn-primary" />
                <a href="{% url 'app:my_contest_detail' project.contest.pk %}">
                    <input type="button" value="Отмена" class="btn btn-default" />
                </a>
            </form>
        </div>
    </div>
{% endblock %}

PocketJudgeServer/app/templates/app/projects-table.html
{% if projects|length > 0 %}
    <table class="table table-bordered table-responsive table-striped table-hover">
        <thead>
            <th>Наименование проекта</th>
            <th>Сумма баллов</th>
        </thead>
        <tbody>
        {% load projects_sums %}
        {% for name, sum in projects|projects_sums %}
            <tr>
                <td>{{ name }}</td>
                <td class="col-xs-5">{{ sum }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}